### PR TITLE
Fix continue for

### LINKED ISSUE #63: continue for causes formatting to be not indented properly
Before
```
function ArrayRemoveAt(array as object, index as integer) as integer
    result = []
    for i = 0 to array.Count() - 1
        if i = index
            ' continue for
        end if
        result.push(array[i])
    end for
    return result
end function
```
After
```
function ArrayRemoveAt(array as object, index as integer) as integer
    result = []
    for i = 0 to array.Count() - 1
        if i = index
            continue for
            end if
            result.push(array[i])
        end for
        return result
    end function
```

### PR DESCRIPTION
**Pull request by iBicha**
Closes #63

### CODE REVIEW

**Review by TwitchBronBron — CHANGES_REQUESTED** [review]
This looks great! We don't have dedicated `Continue For` or `Continue While` tokens in brighterscript because the word `continue` may be used as an variable/function name, so this PR is exactly how I would have implemented it as well! Thanks for putting the time in. 

The CI failed because of some formatting issues. can you please fix them, and then this is good to go!

image

**Review by TwitchBronBron — APPROVED** [review]

**Comment by iBicha** [comment]
@TwitchBronBron I tried, but it is not working.
In 1.6.20, I inspected the transpiled `IndentFormatter.js` file, and the change is not included.
Was there a missing build step perhaps?

**Comment by TwitchBronBron** [comment]
Oh. Silly me. When I was doing the latest vscode release, I forgot to also do this formatter release. I was mistaken, this has not been released yet. Sorry for the mixup. I'll start cutting this release today and let you know when it's actually released.

**Comment by iBicha** [comment]
> Oh. Silly me. When I was doing the latest vscode release, I forgot to also do this formatter release. I was mistaken, this has not been released yet. Sorry for the mixup. I'll start cutting this release today and let you know when it's actually released.

I did not have a change to check, but now I confirm this works. Thanks!

**Pull request merged**
